### PR TITLE
fix 1426

### LINKED ISSUE #1426: golint warnings on consensus/util/messagefan.go
## Description

messagefan.go:33:1: comment on exported type Message should be of the form "Message ..." (with optional leading article)
messagefan.go:54:1: comment on exported method MessageFan.RegisterChannel should be of the form "RegisterChannel ..."
## Describe How to Reproduce

run golint

submitting a PR for this

### PR DESCRIPTION
**Pull request by christo4ferris**
## Description

clean up golint warnings in message fan.go
## Motivation and Context

Fixes #1426 
## How Has This Been Tested?

no new tests warranted for this fix
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
LGTM via manual review. Travis failed due to timeout.

File: common/ledger/util/leveldbhelper/leveldb_provider.go [hunk 1]
```diff
@@ -172,15 +173,19 @@ func (h *DBHandle) WriteBatch(batch *UpdateBatch, sync bool) error {
...
 	eKey := constructLevelKey(h.dbName, endKey)
 	if endKey == nil {
 		// replace the last byte 'dbNameKeySep' by 'lastKeyIndicator'
 		eKey[len(eKey)-1] = lastKeyIndicator
 	}
 	logger.Debugf("Getting iterator for range [%#v] - [%#v]", sKey, eKey)
-	return &Iterator{h.dbName, h.db.GetIterator(sKey, eKey)}
+	itr := h.db.GetIterator(sKey, eKey)
+	if err := itr.Error(); err != nil {
+		return nil, errors.Wrapf(err, "internal leveldb error while obtaining db iterator")
```
Comment (manish-sethi) [inline common/ledger/util/leveldbhelper/leveldb_provider.go]: You may like to call `itr.Release()`, before returning error
