### PR TITLE
Deduplicate requests based on last execution time

### LINKED ISSUE #1931: All peers report identical blockchains that contain duplicated transactions
## Description

~~This is a very rare failure mode that I have only seen 3 or 4 times now. This
is the reason that I added the "duplicate check" to the "checkAgreement"
script.~~

This error appears to be 100% repeatable on my system when run as described under **How to Reproduce**, always showing 11 to 15 duplicates.

We see from the busywork/counters/driver script that all peers appear to be
working perfectly : The counts are correct and the blockchains are
identical. However, it turns out in this case that 11 transactions have been
duplicated at the end of every blockchain. Note that the duplicates come from
all over the place. (I should say that based on the responses to the
chain/blocks API it would _appear_ that the transactions were duplicated, but
I have no other knowledge of the actual internal state of the system.)

I've attached the contents of the BUSYWORK_HOME directory. Unfortunately
this run did not have DEGUG-level logs.

[busywork.tar.gz](https://github.com/hyperledger/fabric/files/324446/busywork.tar.gz)

```
network: ../bin/userModeNetwork -batch 4
network: Creating a pristine environment
network:     Killing all peer and membersrvc processes
network:     Killing all running and stopped Docker containers
network:     Removing all chaincode containers
network:     Cleaning out BUSYWORK_HOME
network:     Cleaning out /var/hyperledger
network: Running with PBFT Batch consensus
network: Network Port and PID Map:
network: ------------------------------------------------------------
network:  PeerID |  gRPC  |  REST | Events |  CLI  | Profile |  PID 
network: ------------------------------------------------------------
network:     vp0 |  38333 | 33346 |  45344 | 44592 |  45596  | 38178
network:     vp1 |  42073 | 33389 |  41646 | 42326 |  41317  | 38182
network:     vp2 |  41149 | 38904 |  46806 | 37063 |  35758  | 38190
network:     vp3 |  45836 | 46428 |  35879 | 40957 |  42482  | 38198
network: ------------------------------------------------------------
network: Waiting for peers to start
network: Network is up
driver: ./driver -clients 1 -transactions 16384 -peerBurst 10 -netBurst 10 -interlock -keepLog -checkAgreement -dupCheck
driver: List of targeted peers with REST API ports
driver:     0.0.0.0:33346
driver:     0.0.0.0:33389
driver:     0.0.0.0:38904
driver:     0.0.0.0:46428
driver: 1 chaincode(s) will be deployed
driver: 1 array(s) will be defined per chaincode
driver: 1 clients will be activated
driver: 16384 transaction(s) will be issued to each array
driver: 16384 total transaction(s) will be issued
driver: busywork::Logger : Logging to /home/bcbrock/.busywork/fabricLog
driver: The log file will persist after exit
driver: Security is disabled
driver: Deploying chaincode(s)
driver: Deployed cc0 as 2ee2fc5851a4c162bc728482c3b1e2d1bb965ab3eca6eb0bd9bb65e8df23677de64f822c6a936310105920a9f34718a9a1b272f3aee0db3c28a27cd50f87b7ef
driver: Waiting up to 5m for chaincode deployments to be registered
driver: Waiting up to 5m for all chaincode containers to be running
driver: Waiting 10s to give chaincode(s) time to initialize
driver: Waiting up to 60s for array creation to be registered
driver: Spawning clients:
driver:     Client 0 is subprocess 44863 with seed 280399412
driver: Waiting (indefinitely) for subprocesses to complete
driver: Transaction rate : 648.35 per second (16384 / 25.270196)
driver: Waiting up to 10s for block-height consensus
driver: Checking consistency of the final state
driver: Checking for agreement between the peers
checkAgreement: Blockchain logs will be written into /home/bcbrock/.busywork
checkAgreement: Logging 0.0.0.0:33346 into /home/bcbrock/.busywork/0.0.0.0:33346.chain
checkAgreement: Logging 0.0.0.0:33389 into /home/bcbrock/.busywork/0.0.0.0:33389.chain
checkAgreement: Logging 0.0.0.0:38904 into /home/bcbrock/.busywork/0.0.0.0:38904.chain
checkAgreement: Logging 0.0.0.0:46428 into /home/bcbrock/.busywork/0.0.0.0:46428.chain
checkAgreement: Checking agreement
checkAgreement: Checking for duplicates in file /home/bcbrock/.busywork/0.0.0.0:46428.chain
checkAgreement:   8201 Blocks; 1 Deploys; 16396 Invokes
checkAgreement:ERROR:   Duplicate Report : 11 Duplicated Transactions
checkAgreement:ERROR:     <TX ID>                              <Line Numbers>
checkAgreement:ERROR:     4d2aa7d6-82ea-42f5-80af-71631abd3693 847 24582
checkAgreement:ERROR:     ad68e796-8933-418b-b0ad-91249bdb0c74 1339 24583
checkAgreement:ERROR:     cb8097e1-48f8-4bc6-8fba-60d58778042a 4012 24585
checkAgreement:ERROR:     f8496d09-c4e5-4f76-a1ac-b58b2c989ddc 4042 24586
checkAgreement:ERROR:     b392f217-f132-452f-96d3-3fc6ce620d31 4435 24588
checkAgreement:ERROR:     6ca279dd-2e1f-4943-93d2-dde763e89ba9 8305 24589
checkAgreement:ERROR:     e7f2b363-0c10-4eb6-8a8a-29a207e2b518 9781 24591
checkAgreement:ERROR:     d6d7aefa-3850-4568-94dd-06eb6870a0e4 10594 24592
checkAgreement:ERROR:     6a9c3884-20bc-4f79-acbb-e523db9faf86 16675 24594
checkAgreement:ERROR:     df94dd1a-a140-4af8-a102-a67fb36eb4f4 1987 24596
checkAgreement:ERROR:     e3659e4b-6d30-4bd7-a537-7c4e12d2ceae 12076 24597
checkAgreement:ERROR: Aborting due to errors, disgreement or duplicates; All log files have been kept
driver:ERROR: Peer agreement check failed
driver:ERROR: Aborting due to errors, mismatches or disagreements above
private.mk:3: recipe for target 's2b' failed
```
## Describe How to Reproduce

This issue was observed on an X86 server running

```
commit 6d873142362f2e6314ca138defa792dcc52b4f10
Merge: 77f7077 6ea2c1e
Author: Binh Q Nguyen <binhn@us.ibm.com>



Date:   Mon Jun 20 11:28:41 2016 -0400

    Merge pull request #1912 from mrshah-at-ibm/chaincode_tls

    Chaincode tls
```

The busywork Make target is below; This failure occurred on the first test (single client). Note that I am using busywork test code that has not been merged yet.

```
.PHONY: s2b 
s2b:
    for clients in 1 2 4 8 16 32; do \
    CORE_PBFT_GENERAL_TIMEOUT_REQUEST=5s \
    CORE_PBFT_GENERAL_TIMEOUT_VIEWCHANGE=5s \
    CORE_PBFT_GENERAL_VIEWCHANGEPERIOD=0 \
    CORE_PBFT_GENERAL_NULLREQUEST=1s \
    $(NETWORK) -batch 4; sleep 10; \
    set -e; ./driver \
        -clients $$clients \
        -transactions $$((16384 / $$clients)) \
        -peerBurst 10 -netBurst 10 \
        -interlock \
        -keepLog \
        -checkAgreement -dupCheck; \
    done
```

### PR DESCRIPTION
**Pull request by jyellick**
## Description

This changeset adds back in a portion of the deduplication logic which was removed.  Specifically, it will cause a replica to ignore any requests from a peer which are timestamped prior to the timestamp of the most recently executed request from that peer.

Note, there is only one new commit here, but it is built upon some other outstanding PRs.
## Motivation and Context

This is a stopgap measure, designed to fix #1931 until a more permanent solution can be found.

The problem is that deduplicating in this manner allows request censorship by the primary.  A malicious primary may choose to execute a later request from a replica to effectively censor the request from before it.  This problem is solved in the paper by having only one outstanding request per client (and consequently, no second later request can be executed).  This is not practical for the fabric, as VPs are clients.  A better solution is being actively pursued.

After a little though, and input from @bcbrock I think this should probably go into the 0.5 release.  Without this PR, we see bad behavior in the non-byzantine case.  With it we expose ourselves to manipulation by byzantine behavior.  Especially for 0.5, I think the non-byzantine case must be the priority.  Still I'd invite opinions from others, especially @kchristidis, @corecode, @tuand27613.
## How Has This Been Tested?

This has been tested against the busywork stress2b test.  CI will cover additionally.
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [X] I have either added documentation to cover my changes or this change requires no new documentation.
- [X] I have either added unit tests to cover my changes or this change requires no new tests.
- [X] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: Jason Yellick jyellick@us.ibm.com

### CODE REVIEW

**Comment by tuand27613** [comment]
+1 on having this in 0.5   .  We want to show that the "happy path" case works.  The byzantinecase can be handled after we prove that the clean case works.

**Comment by srderson** [comment]
Another +1 for adding this to the 0.5 branch based issue @bcbrock discovered. Will wait for review from others.

File: consensus/obcpbft/obc-batch.go [hunk 1]
```diff
@@ -310,6 +316,11 @@ func (op *obcBatch) processMessage(ocMsg *pb.Message, senderHandle *pb.PeerID) e
 	}
 
 	if req := batchMsg.GetRequest(); req != nil {
+		if !op.deduplicator.IsNew(req) {
```
Comment (corecode) [inline consensus/obcpbft/obc-batch.go:319]: I have a vague feeling that the check shouldn't be at this point, because execution and request proposal are not serialized the same way on all replicas.  Probably test on pre-prepare or maybe execute?

Comment (jyellick) [inline consensus/obcpbft/obc-batch.go:319]: I think this is okay here.  Assuming the non-byzantine case (this patch acknowledges that it enables censorship in the byzantine case), there are really only two scenarios.
1. We have executed the request, or a later request.  In which case it does not make it into our outstanding requests, and we discard it.
2. We have not executed the request or any later request.  In this case, we will add it to our outstanding requests.  If the request has already prepared, this is not a problem, as if we are the primary, it is already in our list of `pendingRequests`, so we will not order it a second time.  If we are not the primary, then we will build the `pendingRequests` list after the view change, also ensuring we do not doubly execute.

Comment (corecode) [inline consensus/obcpbft/obc-batch.go:319]: My concern is that execution and request reception is not serialized the same way on all replicas, so some might reject the request while others will accept it.  I guess as long as the primary is attaching the request again, we should be fine.

**Comment by corecode** [comment]
Even though we are still discussing on specifics, in principle this PR can go in.

**Comment by srderson** [comment]
Thanks @corecode. Will merge this into the 0.5 branch.
