### PR TITLE
core/rest: Fix panic when block not found in DB

### LINKED ISSUE #2012: Panic: "invalid memory address or nil pointer dereference" in response to /chain/blocks/<N> API
## Description

This is a panic that appears to be coming from the /chain/blocks/<N> API.  The panic is not fatal, but is being caught by the gocraft/web stuff, which carries on. However it does cause the test to fail (or, I assume this is what's causing it to fail.)

Here is the log file of the failing peer. The panic is buried in the middle of it.

[stderr.txt](https://github.com/hyperledger/fabric/files/332807/stderr.txt)
## Describe How to Reproduce

I am not yet sure if this is reproducible. Here is the context:

```
commit 2aeddd6929d7108bda6a498d1d64e771177c5270
Merge: ef5c8c7 99bf9b3
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Fri Jun 24 17:41:14 2016 -0400

    Merge pull request #1915 from frankyclu/issue-1844-workaround

    Issue 1844 (multi-account with TCert attributes) workaround
```

This is the soon-to-be "official" form of the busywork `stress2b` test I was trying to run:

```
STRESS2 = ./driver \
        -transactions 10000 \
        -peerBurst 10000 \
        -interlock \
        -keepLog \
        -checkAgreement -dupCheck

STRESS2_CONFIG = \
    @CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST=3s \
    CORE_PEER_VALIDATOR_CONSENSUS_BUFFERSIZE=100000 

stress2b: 
    @$(STRESS2_CONFIG) \
    $(NETWORK) -batch 4
    @echo "makefile: Sleeping 10 seconds to allow peers to interlock"; sleep 10
    @$(STRESS2)

```

### PR DESCRIPTION
**Pull request by dubek**
## Description

When querying REST API using `/chain/blocks/N`, if N refers to a block which is _lower_ than the current chain height but the block doesn't exist in the DB, the REST API panics.  This PR fixes this.
## Motivation and Context

This deals with a `nil,nil` response from `ledger.GetBlockByNumber`; see #1610 for discussion whether this response should be valid at all.

Fixes #2012
## How Has This Been Tested?

Current REST API unit tests past. Unfortunately, I could find a way to mimic this scenario in unit tests - I tried reducing `deltaHistorySize` to 3 but it only deletes records from the state delta columnfamily and not from the blocks columnfamily. If anyone has an idea how to cause this scenario in the unit-tests, please let me know and I'll add it.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

The continuous integration build process will run [make checks](https://github.com/hyperledger/fabric/blob/master/Makefile#L22) to confirm that tests pass and that code quality meets minimum standards. You may optionally run this locally as PRs will not be accepted until they pass.

Signed-off-by: Dov Murik dmurik@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
@dubek For the test, could you call ledger.PutRawBlock directly and add some fake block larger than the current chain height, and then GET `/chain/blocks/N` where N is a value between the actual chain height and the fake block that you added?

**Comment by dubek** [comment]
@srderson Thanks for the advice - it worked (indeed triggers the `nil,nil` response). I added the test case and rebased on top of master.

**Comment by srderson** [comment]
Thanks, LGTM

File: common/ledger/blockledger/fileledger/factory.go [hunk 1]
```diff
@@ -54,8 +54,8 @@ func (f *fileLedgerFactory) GetOrCreate(channelID string) (blockledger.ReadWrite
 }
 
 // Remove removes an existing ledger and its indexes. This operation
-// is blocking.
-func (f *fileLedgerFactory) Remove(channelID string) error {
+// performs an async deletion.
+func (f *fileLedgerFactory) Remove(channelID string, finishRemove func(string, bool)) error {
```
Comment (tock-ibm) [inline common/ledger/blockledger/fileledger/factory.go]: I think a better approach would be to implement the asynchrony in the Registrar, launching the go routine over there.

File: common/ledger/blockledger/fileledger/factory.go [hunk 2]
```diff
@@ -70,10 +70,15 @@ func (f *fileLedgerFactory) Remove(channelID string) error {
...
-	}
+	go func() {
+		err := f.blkstorageProvider.Drop(channelID)
+		if err != nil {
+			logger.Info(err.Error())
+			finishRemove(channelID, false)
+		} else {
+			finishRemove(channelID, true)
+		}
+	}()
```
Comment (tock-ibm) [inline common/ledger/blockledger/fileledger/factory.go]: The problem here is that the Drop() will be executed with one routine, and the rest will execute with another.... the channelID will be removed from the ledger, the .remove file removed from the file repo... all this while for a long Drop() the other goroutine is still working. This will break the crash fault tolerance.

File: common/ledger/blockledger/fileledger/factory.go [hunk 3]
```diff
@@ -70,10 +70,15 @@ func (f *fileLedgerFactory) Remove(channelID string) error {
 		return err
 	}
```
Comment (tock-ibm) [inline common/ledger/blockledger/fileledger/factory.go]: I think the `removeFileRepo.Save()` should execute before the `blockStore.Shutdown()`, no?
I seems to me `removeFileRepo.Save()`  should be the first think we do.

File: orderer/common/multichannel/registrar.go [hunk 4]
```diff
@@ -60,7 +60,8 @@ type Registrar struct {
 	bccsp              bccsp.BCCSP
 	clusterDialer      *cluster.PredicateDialer
 
-	joinBlockFileRepo *filerepo.Repo
+	joinBlockFileRepo, removeFileRepo *filerepo.Repo
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: I don't think we should expose the `removeFileRepo` here, but rather keep internal to the `fileledger` if we can

File: orderer/common/multichannel/registrar.go [hunk 5]
```diff
@@ -102,41 +103,53 @@ func NewRegistrar(
...
-	r.init(consenters)
+	r.init(consenters, "")
 
 	r.lock.Lock()
 	defer r.lock.Unlock()
 	r.startChannels()
 }
 
-func (r *Registrar) init(consenters map[string]consensus.Consenter) {
+func (r *Registrar) init(consenters map[string]consensus.Consenter, systemChannelID string) {
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: we don't need that `systemChannelID string`

File: orderer/common/multichannel/registrar.go [hunk 6]
```diff
@@ -188,19 +204,22 @@ func (r *Registrar) discoverLedgers(channelsWithJoinBlock map[string]*cb.Block)
 		if rl.Height() == 0 {
 			if _, ok := channelsWithJoinBlock[channelID]; !ok {
 				logger.Warnf("Channel '%s' has an empty ledger without a join-block, removing it", channelID)
-				if err := r.ledgerFactory.Remove(channelID); err != nil {
+				if err := r.ledgerFactory.Remove(channelID, r.removeChannelFromPendingRemovals); err != nil {
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: This for example should be done synchronously, as it is a small ledger, and we don't want to start before it is deleted

File: common/ledger/blockledger/fileledger/factory.go [hunk 7]
```diff
@@ -115,24 +120,10 @@ func New(directory string, metricsProvider metrics.Provider) (blockledger.Factor
...
-		for _, fileName := range files {
-			channelID := factory.removeFileRepo.FileToBaseName(fileName)
-			err = factory.Remove(channelID)
-			if err != nil {
-				logger.Errorf("Failed to remove channel %s: %s", channelID, err.Error())
-				return nil, err
-			}
-			logger.Infof("Removed channel: %s", channelID)
-		}
-	}
```
Comment (tock-ibm) [inline common/ledger/blockledger/fileledger/factory.go]: why was this removes / moved? 
In addition, because the filerepo .remove file is deleted before the Drop() completed, we could be missing on the retry of removals that crashed in the middle of a Drop...

File: orderer/common/multichannel/registrar.go [hunk 8]
```diff
@@ -61,6 +61,7 @@ type Registrar struct {
 	clusterDialer      *cluster.PredicateDialer
 
 	joinBlockFileRepo *filerepo.Repo
+	pendingRemoval    map[string]bool
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: A nit: I would place the `pendingRemoval` in the block of fields below the `lock` right below `follower`, to send the message that it is a fields that  should be accessed with the lock. (In contrast to all the rest that are initialized upon creation and stay static throughout).

File: orderer/common/multichannel/registrar.go [hunk 9]
```diff
@@ -102,6 +103,7 @@ func NewRegistrar(
 		callbacks:          callbacks,
 		bccsp:              bccsp,
 		clusterDialer:      clusterDialer,
+		pendingRemoval:     make(map[string]bool),
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: As above, place this field below `followers`.

File: orderer/common/multichannel/registrar.go [hunk 10]
```diff
@@ -696,6 +698,11 @@ func (r *Registrar) JoinChannel(channelID string, configBlock *cb.Block, isAppCh
 	r.lock.RLock()
 	defer r.lock.RUnlock()
 
+	removalStatus, ok := r.pendingRemoval[channelID]
+	if removalStatus && ok {
+		return types.ChannelInfo{}, types.ErrChannelNotExist
+	}
+
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: Two things:
1. I think this is the wrong error to return. As long as the channel is pending removal, it "exists". So maybe define a new type:
```
var ErrChannelPendingRemoval = errors.New("channel pending removal")
```
If you do this, check how this new error type affects the REST API handler behavior. 
The minimum I would do is to use `ErrChannelExists`.

2. `pendingRemoval` is `map[string]bool`, and the cool thing about it is that when the value is missing, false is returned, so you can do this:
```
if pendingRemoval[channelID] {
	return types.ChannelInfo{}, types.ErrChannelPendingRemoval 
}
```

File: orderer/common/multichannel/registrar.go (hunk 8 above)
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: I think that the "List" and "ListAll" should return channels that are pending removal, with:
ClusterRelation = "none"
Status = "pending-remove" (or maybe just reuse "inactive"?)
This way an operator would be able to monitor when a channel was finally removed.

File: orderer/common/multichannel/registrar.go [hunk 11]
```diff
@@ -1044,3 +1041,20 @@ func (r *Registrar) removeSystemChannel() error {
 
 	return nil
 }
+
+func (r *Registrar) removeLedgerAsync(channelID string) {
+	removalStatus, ok := r.pendingRemoval[channelID]
+	if removalStatus && ok {
+		return
+	}
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: I think this is redundant, because we only get here if the channel is in either in the followers or channels map, but never in the pendingRemoval map... If anything, this signals an error condition, no?

File: orderer/common/multichannel/registrar.go [hunk 12]
```diff
@@ -1044,3 +1041,20 @@ func (r *Registrar) removeSystemChannel() error {
...
+
+	r.pendingRemoval[channelID] = true
+	go func() {
+		if err := r.ledgerFactory.Remove(channelID); err != nil {
+			r.pendingRemoval[channelID] = false
+			logger.Errorf("Ledger factory failed to remove empty ledger '%s', error: %s", channelID, err)
+			return
+		}
+		delete(r.pendingRemoval, channelID)
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go:1098]: Must take the lock to delete from the r.pendingRemoval map.

File: orderer/common/multichannel/registrar_test.go [hunk 13]
```diff
@@ -1543,6 +1565,60 @@ func TestRegistrar_RemoveChannel(t *testing.T) {
...
+		require.NotContains(t, ledgerFactory.ChannelIDs(), "my-raft-channel")
+		info, err := registrar.JoinChannel("my-raft-channel", genesisBlockAppRaft, true)
+		require.NoError(t, err)
+		require.Equal(t, types.ChannelInfo{Name: "my-raft-channel", URL: "", ClusterRelation: "member", Status: "active", Height: 1}, info)
+		require.NotNil(t, registrar.GetChain("my-raft-channel"))
+		require.Contains(t, ledgerFactory.ChannelIDs(), "my-raft-channel")
+
+		registrar.pendingRemoval["my-raft-channel"] = true
+		err = registrar.RemoveChannel("my-raft-channel")
+		require.NoError(t, err)
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar_test.go]: I would actually have this return `ErrChannelPendingRemove`

File: orderer/common/multichannel/registrar_test.go [hunk 14]
```diff
@@ -1543,6 +1565,60 @@ func TestRegistrar_RemoveChannel(t *testing.T) {
...
+
+		// After removing the channel, it no longer exists in the registrar or the ledger
+		require.Nil(t, registrar.GetChain("my-raft-channel"))
+		require.Equal(t, len(ledgerFactory.ChannelIDs()), 1)
+		require.Contains(t, ledgerFactory.ChannelIDs(), "my-raft-channel")
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar_test.go]: You say in the comment it is not in the ledger, but verify that it is?

File: orderer/common/multichannel/registrar.go [hunk 15]
```diff
@@ -908,17 +916,12 @@ func (r *Registrar) RemoveChannel(channelID string) error {
 	return types.ErrChannelNotExist
 }
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go:948]: I think we need to check if it is pendingRemoval, and if so, return another error: 
`var ErrChannelPendingRemoval = errors.New("channel pending removal")`

File: orderer/common/multichannel/registrar.go [hunk 16]
```diff
@@ -48,6 +48,7 @@ type Registrar struct {
 	lock            sync.RWMutex
 	chains          map[string]*ChainSupport
 	followers       map[string]*follower.Chain
+	pendingRemoval  sync.Map
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: The use of sync.Map is not needed here. The map is mostly used within the `lock`.
All you have to do is when the goroutine you assign to remove finishes, delete the key from the map under a lock. Referring to your earlier commit:

```
func (r *Registrar) removeLedgerAsync(channelID string) {
	removalStatus, ok := r.pendingRemoval[channelID]
	if removalStatus && ok {
		return
	}

	r.pendingRemoval[channelID] = true
	go func() {
		if err := r.ledgerFactory.Remove(channelID); err != nil {
			r.pendingRemoval[channelID] = false
			logger.Errorf("Ledger factory failed to remove empty ledger '%s', error: %s", channelID, err)
			return
		}
                r.lock.Lock() \\<<<
		delete(r.pendingRemoval, channelID)
                r.lock.Unlock() \\<<<
	}()
}
```
So you can use map[string]bool as you did before.

See [here](https://golang.org/pkg/sync/#Map) and [here](https://medium.com/@deckarep/the-new-kid-in-town-gos-sync-map-de24a6bf7c2c), that explain that the `sync.Map` is better avoided unless you hit a very specific use-case.

File: orderer/common/multichannel/registrar.go [hunk 17]
```diff
@@ -696,6 +698,11 @@ func (r *Registrar) JoinChannel(channelID string, configBlock *cb.Block, isAppCh
 	r.lock.RLock()
 	defer r.lock.RUnlock()
 
+	removalStatus, ok := r.pendingRemoval.Load(channelID)
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: map[string]bool will do fine, as explained above. Here it is protected by `r.lock`.

File: orderer/common/multichannel/registrar.go [hunk 18]
```diff
@@ -886,6 +893,12 @@ func (r *Registrar) joinSystemChannel(
 func (r *Registrar) RemoveChannel(channelID string) error {
 	r.lock.Lock()
 	defer r.lock.Unlock()
+
+	removalStatus, ok := r.pendingRemoval.Load(channelID)
+	if ok && removalStatus.(bool) {
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: map[string]bool will do fine, as explained above. Here it is protected by `r.lock`.

File: orderer/common/multichannel/registrar.go [hunk 19]
```diff
@@ -1002,10 +1008,26 @@ func (r *Registrar) removeSystemChannel() error {
 	r.systemChannel.Halt()
 	delete(r.chains, systemChannelID)
 
+	pendingRemovals := []string{}
+
 	// halt all application channels
 	for channel, cs := range r.chains {
 		cs.Halt()
+		pendingRemovals = append(pendingRemovals, channel)
+	}
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: This is just a list of all the channels.... I think it is simpler to append to this list only if the channel does not include the orderer in the consenters set... that is, move the part that computes the `isChannelMember` in the second loop here, and then the second loop will be simpler, as it would iterate on channels that actually need to be removed.

File: orderer/common/channelparticipation/restapi.go [hunk 20]
```diff
@@ -289,6 +290,8 @@ func (h *HTTPHandler) serveRemove(resp http.ResponseWriter, req *http.Request) {
 		h.sendResponseNotAllowed(resp, errors.WithMessage(err, "cannot remove"), http.MethodGet)
 	case types.ErrChannelNotExist:
 		h.sendResponseJsonError(resp, http.StatusNotFound, errors.WithMessage(err, "cannot remove"))
+	case types.ErrChannelPendingRemoval, types.ErrChannelRemoval:
+		h.sendResponseJsonError(resp, http.StatusConflict, errors.WithMessage(err, "cannot remove"))
```
Comment (tock-ibm) [inline orderer/common/channelparticipation/restapi.go]: `types.ErrChannelRemoval` - I suggest `types.ErrChannelRemovalFailure`, to be more explicit.
In addition, I think it should return the error code "InternalServerError" 500. What do you think?

File: orderer/common/multichannel/registrar.go [hunk 21]
```diff
@@ -1014,31 +1057,44 @@ func (r *Registrar) removeSystemChannel() error {
...
+			delete(r.chains, channel)
 		}
 	}
 
-	// remove system channel resources
-	err := r.ledgerFactory.Remove(systemChannelID)
-	if err != nil {
-		return errors.WithMessagef(err, "error removing ledger for system channel %s", r.systemChannelID)
+	if len(failedRemovals) > 0 {
+		return fmt.Errorf("failed removing %s ledger for channel(s)", strings.Join(failedRemovals, ", "))
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go]: I suggest:
`fmt.Errorf("failed removing ledger for channel(s): %s", strings.Join(failedRemovals, ", "))

File: orderer/common/multichannel/registrar.go [hunk 22]
```diff
@@ -1014,31 +1057,44 @@ func (r *Registrar) removeSystemChannel() error {
...
 	return nil
 }
+
+func (r *Registrar) removeLedgerAsync(channelID string) {
+	r.pendingRemoval[channelID] = true
+
+	go func() {
+		if err := r.ledgerFactory.Remove(channelID); err != nil {
+			r.lock.Lock()
+			r.pendingRemoval[channelID] = false
```
Comment (tock-ibm) [inline orderer/common/multichannel/registrar.go:1092]: I like this idea. Please put a comment on the map that clarifies what the boolean means, i.e. "True=pending, False=removal-failed", etc.

File: orderer/common/channelparticipation/restapi.go [hunk 23]
```diff
@@ -254,8 +254,9 @@ func (h *HTTPHandler) sendJoinError(err error, resp http.ResponseWriter) {
 		// The client is trying to join an app-channel that exists, but the system channel does not;
 		// The client is trying to join the system-channel, and it exists. GET & DELETE are allowed on the channel.
 		h.sendResponseNotAllowed(resp, errors.WithMessage(err, "cannot join"), http.MethodGet, http.MethodDelete)
-	case types.ErrAppChannelsAlreadyExists:
+	case types.ErrAppChannelsAlreadyExists, types.ErrChannelPendingRemoval:
```
Comment (tock-ibm) [inline orderer/common/channelparticipation/restapi.go]: I think there should be a symmetry between the "Join" & "Remove" w.r.t. `types.ErrChannelPendingRemoval` - i.e. both should respond with "Conflict" to reflect the transitory nature of the error.

In addition, "Join" does not handle `types.ErrChanneRemovalFailure` as the "Remove" below, and it would fall through to the "Bad Request" which is not what we want. I think this should return "500 Internal Server Error", since this  is the server's fault, not a state or a bad request, something that the user can do anything about. What do you think?

File: orderer/common/multichannel/registrar_test.go [hunk 24]
```diff
@@ -1543,6 +1571,119 @@ func TestRegistrar_RemoveChannel(t *testing.T) {
...
+
+		require.Nil(t, registrar.GetChain("my-raft-channel"))
+		require.NotContains(t, ledgerFactory.ChannelIDs(), "my-raft-channel")
+		info, err := registrar.JoinChannel("my-raft-channel", genesisBlockAppRaft, true)
+		require.NoError(t, err)
+		require.Equal(t, types.ChannelInfo{Name: "my-raft-channel", URL: "", ClusterRelation: "member", Status: "active", Height: 1}, info)
+		require.NotNil(t, registrar.GetChain("my-raft-channel"))
+		require.Contains(t, ledgerFactory.ChannelIDs(), "my-raft-channel")
+
+		// This will force the failure of the underlying factory.Remove() because the pendingops/remove will not exist
```
[the remark this answers is not in the document]
Comment (tock-ibm) [reply orderer/common/multichannel/registrar_test.go:1711]: I like this idea. This goes towards what we want to achieve in this issue [FAB-18106](https://jira.hyperledger.org/browse/FAB-18106). The intention in that task is that a channel that fails catastrophically will stop and report a new status `types.StatusFailure` instead of panicking and crashing the server. 

If we had that error code already, I would be inclined to suggest that the map would include a struct with
```
{
  cRel     types.ClusterRelation
  status  types.Status
}
```
you could then insert into the map {"member", "inactive"} or {"follower", "inactive"} when you start the removal, delete that when removal ends successfully, and put  {"member", "failure"} or {"follower", "failure"} if something goes wrong.
What do you think? This can be done  in this task or open another Jira for it - up to you.

File: orderer/common/types/errors.go [hunk 25]
```diff
@@ -21,3 +21,9 @@ var ErrAppChannelsAlreadyExists = errors.New("application channels already exist
 
 // ErrChannelNotExist is returned when trying to remove or list a channel that does not exist
 var ErrChannelNotExist = errors.New("channel does not exist")
+
+// ErrChannelPendingRemoval is returned when trying to remove or list a channel that is being removed.
+var ErrChannelPendingRemoval = errors.New("channel pending removal")
+
+// ErrChannelRemoval is returned when a removal attempt failure has been recorded.
+var ErrChannelRemoval = errors.New("channel removal failure")
```
Comment (tock-ibm) [inline orderer/common/types/errors.go]: I think 
`var ErrChannelRemovalFailure = errors.New("channel removal failure")`
is clearer
