### PR TITLE
Resend view change requests periodically if quorum is not achieved

### LINKED ISSUE #1917: PBFT transient network failure tolerance
## Description

In my testing of #1877 I encountered a scenario which, to my best reading of the Castro paper does not seem to be handled by the PBFT protocol.  I'd appreciate comments from @vukolic and @cca88 in particular, but @corecode, @kchristidis, and @tuand27613 might have some insight as well.

Scenario:
1. Start a network of 4 replicas, vp0, vp1, vp2, vp3
2. Have vp0 successfully establish a link to vp1, vp2, vp3
3. Broadcast request to all VPs, via vp0
4. Request fails to prepare (because vp1, vp2, vp3 are not linked to eachother)
5. All replicas send view change, vp0 has 4 view change messages, all other replicas have 2
6. vp0 has its new-view timer expire because after receiving 3+ view change messages it did not receive a new view in time
7. vp1, vp2, vp3 are not in an active view, and do not have enough view change messages to start the new view timer.
8. Network connectivity is established between vp1, vp2, vp3
9. The network will never process another request, even if more are submitted, or periodic null request, or periodic view changes are enabled.

I think the simple answer is 'Failure to connect between vp1, vp2, vp3, counts are more than 1 fault, and the PBFT promises are off'.  However, permanently failing because of this transient error seems like a serious problem.

Proposed fix: In addition to the 'new-view timer', we could start a 'view change rebroadcast timer', so that, for as long as a replica is in a view change, but does not have sufficient view change messages to start the new view timer, it will periodically rebroadcast its view-change message, in case for whatever reason its previous view change message was not delivered to all replicas.

### PR DESCRIPTION
**Pull request by jyellick**
## Description

This changeset introduces a new timer which is started after sending a view change message, and stopped when a quorum of view change messages is received.  The timeout is configurable via the `config.yaml`.
## Motivation and Context

This fixes #1917 which contains a detailed scenario which results in PBFT network deadlock.
## How Has This Been Tested?

A new unit test is included, existing CI should be sufficient to cover the remainder.
## Checklist:

- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Jason Yellick jyellick@us.ibm.com

### CODE REVIEW

File: consensus/obcpbft/pbft-core.go [hunk 1]
```diff
@@ -393,6 +403,14 @@ func (instance *pbftCore) ProcessEvent(e events.Event) events.Event {
 		return instance.processNewView()
 	case viewChangedEvent:
 		// No-op, processed by plugins if needed
+	case viewChangeResendTimerEvent:
+		if instance.activeView {
+			logger.Warningf("Replica %d had its view change resend timer expire but it's in an active view, this is benign but may indicate a bug", instance.id)
```
Comment (tuand27613) [inline consensus/obcpbft/pbft-core.go:408]: What should users do if they see this warning ?  "may indicate a bug" will get everybody worked up.

Comment (jyellick) [inline consensus/obcpbft/pbft-core.go:408]: They should report it as a bug. This message should never surface in real execution (though it does in our tests).  Perhaps a clearer phrasing is "this is benign, but indicates a bug", I thought 'may' might make people freak out about it a little less, as this check guards against said bug, but it would be a bug, none the less.

**Comment by tuand27613** [comment]
code LGTM

**Comment by kchristidis** [comment]
@srderson This can be closed.

**Comment by srderson** [comment]
@kchristidis Closed or merged? If it should be closed, @jyellick can do that.

**Comment by kchristidis** [comment]
Closed as another resend view change PR has been merged already. @jyellick

UPDATE: Ah, I see what's going on. The PRs are against different branches. Scratch the false alarm, we regret error, etc.

**Comment by srderson** [comment]
Yup, similar PRs in two different branches. Thanks for the review @tuand27613 and @kchristidis. LGTM.
