### PR TITLE
[#1887]Fix incorrect package name

### LINKED ISSUE #1887: Unit Tests are failing - membersrvc/ca/tca.go:266: undefined: protobuf in protobuf.Timestamp
## Description

Observed unit-tests are failing on commit  3df38fe with error message `membersrvc/ca/tca.go:266: undefined: protobuf in protobuf.Timestamp`
## Describe How to Reproduce

git pull commit# 3df38fe and run unit-tests. Below are the log files captured on different environments.
Vagrant - [3df38fe.txt](https://github.com/hyperledger/fabric/files/319803/3df38fe.txt)
Travis - https://travis-ci.org/hyperledger/fabric/builds/138261929

### PR DESCRIPTION
**Pull request by GrapeBaBa**
## Description

Fix incorrect package name.
## Motivation and Context

Fixes #1887 
## How Has This Been Tested?

unit test passed
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by:Kai Chen ckaiwh@cn.ibm.com

### CODE REVIEW

**Comment by adecaro** [comment]
@GrapeBaBa Great :)

**Comment by GrapeBaBa** [comment]
@adecaro Per your finding:)

**Comment by mastersingh24** [comment]
LGTM

**Comment by srderson** [comment]
LGTM

File: orderer/consensus/etcdraft/chain.go [hunk 1]
```diff
@@ -1288,34 +1289,40 @@ func (c *Chain) newConfigMetadata(block *common.Block) *etcdraft.ConfigMetadata
 
 // ValidateConsensusMetadata determines the validity of a
 // ConsensusMetadata update during config updates on the channel.
-func (c *Chain) ValidateConsensusMetadata(oldMetadataBytes, newMetadataBytes []byte, newChannel bool) error {
+func (c *Chain) ValidateConsensusMetadata(oldOrdererConfig, newOrdererConfig channelconfig.Orderer, newChannel bool) error {
 	// metadata was not updated
-	if newMetadataBytes == nil {
+	if newOrdererConfig == nil {
```
Comment (jyellick) [inline orderer/consensus/etcdraft/chain.go:1293]: The config should never be nil here.  We are operating on the config, not the update as we were before.

File: orderer/consensus/etcdraft/chain.go [hunk 2]
```diff
@@ -1328,11 +1335,18 @@ func (c *Chain) ValidateConsensusMetadata(oldMetadataBytes, newMetadataBytes []b
...
 	dummyOldConsentersMap := CreateConsentersMap(dummyOldBlockMetadata, oldMetadata)
-	changes, err := ComputeMembershipChanges(dummyOldBlockMetadata, dummyOldConsentersMap, newMetadata.Consenters, c.support.SharedConfig())
+	changes, err := ComputeMembershipChanges(dummyOldBlockMetadata, dummyOldConsentersMap, newMetadata.Consenters)
 	if err != nil {
 		return err
 	}
 
+	//new config metadata was verified above. Additionally need to check new consenters for certificates expiration
+	for _, c := range changes.AddedNodes {
+		if err := validateConsenterTLSCerts(c, verifyOpts, false); err != nil {
```
Comment (jyellick) [inline orderer/consensus/etcdraft/chain.go:1356]: I'm not sure that we should be checking certificate expiration here.  For instance, we could have an expired certificate that we want to leave in place while we grow or shrink the consenter set.  If we want to check expiration I'd say we need to only check expiration of _new_ certificates.

I'd also note, that the orderer has been modified to perform ID validation not based on cert literals anymore, but rather based on public key, so, in some cases, even if the TLS certificate is expired in the channel config, an orderer with a valid and unexpired TLS certificate with matching public key may successfully be validated using this information.

File: orderer/consensus/etcdraft/util_test.go [hunk 3]
```diff
@@ -7,21 +7,27 @@ SPDX-License-Identifier: Apache-2.0
...
 	"github.com/hyperledger/fabric/protoutil"
+	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
+	"io/ioutil"
+	"path/filepath"
+	"testing"
+)
+
+const (
+	consentersTestDataDir = "testdata/consenters_certs/"
```
Comment (jyellick) [inline orderer/consensus/etcdraft/util_test.go:28]: If you are going to go with fixtures, then they need to be clearly documented on how they can be reproduce.  Since in this case, the fixtures will become unnecessary with the introduction of go v1.15, it would be even better to leave in some commented code or other instructions as to how to remove the fixtures once they are no longer needed.
