### PR TITLE
Fix 1430

### LINKED ISSUE #1430: golint warnings in consensus/helper
## Description

golint warnings in consensus/helper
engine.go:32:6: exported type EngineImpl should have comment or be unexported
engine.go:38:1: exported method EngineImpl.GetHandlerFactory should have comment or be unexported
engine.go:42:1: exported method EngineImpl.ProcessTransactionMsg should have comment or be unexported
engine.go:98:1: exported function GetEngine should have comment or be unexported
handler.go:41:2: exported const DefaultConsensusQueueSize should have comment (or a comment on this block) or be unexported
helper.go:396:1: exported method Helper.GetBlockchainInfoBlob should have comment or be unexported
helper.go:403:1: exported method Helper.GetBlockHeadMetadata should have comment or be unexported
helper.go:416:1: exported method Helper.SkipTo should have comment or be unexported
helper.go:422:1: exported method Helper.Initiated should have comment or be unexported
helper.go:425:1: exported method Helper.Completed should have comment or be unexported
helper.go:429:1: exported method Helper.Errored should have comment or be unexported
## Describe How to Reproduce

run golint

Note: go vet also reports errors but these cannot be resolved until we get a more up-to-date version of go-logging

### PR DESCRIPTION
**Pull request by christo4ferris**
clean golint warnings in consensus/helper
## Description

Cleaned up:
engine.go:32:6: exported type EngineImpl should have comment or be unexported
engine.go:38:1: exported method EngineImpl.GetHandlerFactory should have comment or be unexported
engine.go:42:1: exported method EngineImpl.ProcessTransactionMsg should have comment or be unexported
engine.go:98:1: exported function GetEngine should have comment or be unexported
handler.go:41:2: exported const DefaultConsensusQueueSize should have comment (or a comment on this block) or be unexported
helper.go:396:1: exported method Helper.GetBlockchainInfoBlob should have comment or be unexported
helper.go:403:1: exported method Helper.GetBlockHeadMetadata should have comment or be unexported
helper.go:416:1: exported method Helper.SkipTo should have comment or be unexported
helper.go:422:1: exported method Helper.Initiated should have comment or be unexported
helper.go:425:1: exported method Helper.Completed should have comment or be unexported
helper.go:429:1: exported method Helper.Errored should have comment or be unexported
## Motivation and Context

Fixes #1430
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
LGTM

File: orderer/common/channelparticipation/restapi.go [hunk 1]
```diff
@@ -189,7 +188,10 @@ func (h *HTTPHandler) serveJoin(resp http.ResponseWriter, req *http.Request) {
 // Expect a multipart/form-data with a single part, of type file, with key FormDataConfigBlockKey.
 func (h *HTTPHandler) multipartFormDataBodyToBlock(params map[string]string, req *http.Request, resp http.ResponseWriter) *cb.Block {
 	boundary := params["boundary"]
-	reader := multipart.NewReader(req.Body, boundary)
+	reader := multipart.NewReader(
+		http.MaxBytesReader(resp, req.Body, int64(h.config.MaxRequestBodySize)),
+		boundary,
+	)
 	form, err := reader.ReadForm(100 * 1024 * 1024)
```
Comment (tock-ibm) [inline orderer/common/channelparticipation/restapi.go]: Harmonize  these two limits... (`MaxBytesReader` & `ReadForm`)
IE maybe set the latter to be 2*MaxRequestBodySize ?
