### PR TITLE
Address golint warnings and errors in ca.go (Fixes #1499)

### LINKED ISSUE #1409: The enrollID should not be included in the subject of transaction certificates
## Description

Transaction certificates currently include the enrollID as part of the subject in the X509 public certificate.  Given that tcerts are used for unlink-ability, this needs to be fixed.  
## Describe How to Reproduce

Enable security, use transaction certificates and decode the X509 certs.  Easiest way to do this is to simply extract the cert bytes from the block/transaction API response and decode them

### PR DESCRIPTION
**Pull request by JonathanLevi**
Fixing **golint** errors and warnings in ca.go (and a small change in tca.go to reflect the GroupAffiliation change)
## Description

See an impressive list of golint errors here: [This is part of #[1286](https://github.com/hyperledger/fabric/issues/1286)]
## How Has This Been Tested?

`golint + make all 
`
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: JonathanLevi

### CODE REVIEW

File: membersrvc/ca/ca.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ import (
 
 	"github.com/hyperledger/fabric/core/crypto/primitives"
 	pb "github.com/hyperledger/fabric/membersrvc/protos"
-	_ "github.com/mattn/go-sqlite3"
+	_ "github.com/mattn/go-sqlite3" // TODO: not use a blank import!
```
Comment (ghaskins) [inline membersrvc/ca/ca.go]: Do we know why this was here and why it is now marked TODO?

Blank imports are generally used for one purpose to my knowledge: to force the side-effects of running the modules func init().  

So, my first question is: Did a human or the tooling decide to add that comment.  If a human, what was the rationale?

Second question: is the side-effect inducing behavior desired, or not?  If desired, this needs to stay the way it was.  If it was not desired, we should just remove the import outright.

Comment (JonathanLevi) [inline membersrvc/ca/ca.go]: Hi @ghaskins,
1. Yes I manually added the comment and not the tool. So yes, without loss of generality ;-) and under some assumption, it is relatively safe to claim that it was a **human**.
2. It's true that blank imports are generally used to force the side-effects of running the modules func init()... 

As for the second question, I do understand why it is currently there: Specifically in this case I believe the blank import is used for registering the **sqlite3** driver as a database driver without importing any other functions, kind of a:

`sql.Register("sqlite3", &SQLiteDriver{})`

I believe that the coder's original desired side-effects are/were that further (standard) `sql` calls will refer to the registered `sqlite3` driver, e.g., in:

`db, err := sql.Open("sqlite3", filepath.Join(ksPath, ks.node.conf.getKeyStoreFilename()))
`
in [/core/crypto/node_ks.go#L358](https://github.com/JonathanLevi/fabric/blob/ca8135b1a0f95127c96478518628a65a377ec123/core/crypto/node_ks.go#L358)

Which is why I haven't removed the import altogether.

Keeping in mind that the background to this suggested fix is that I wanted to quickly address the go lint message:

`ca/ca.go:35:2: a blank import should be only in a main or test package, or have a comment justifying it`.

Comment (JonathanLevi) [inline membersrvc/ca/ca.go]: I hope I addressed the questions/concern, otherwise do let me know?
Even though I personally don't like blank imports (or at least avoid them whenever possible), I have also changed the import comment as follows:

```
-       _ "github.com/mattn/go-sqlite3" // TODO: not use a blank import!
+       _ "github.com/mattn/go-sqlite3" // TODO: justify this blank import or remove
```

Please kindly let me know if these address the questions and concerns, or otherwise? Thanks.

Comment (srderson) [inline membersrvc/ca/ca.go]: Looks good. Agree it should be justified to help people understand why it was used.

File: membersrvc/ca/ca.go [hunk 2]
```diff
@@ -33,7 +33,7 @@ import (
 
 	"github.com/hyperledger/fabric/core/crypto/primitives"
 	pb "github.com/hyperledger/fabric/membersrvc/protos"
-	_ "github.com/mattn/go-sqlite3" // TODO: not use a blank import!
+	_ "github.com/mattn/go-sqlite3" // TODO: justify this blank import or remove
```
Comment (JonathanLevi) [inline membersrvc/ca/ca.go:36]: @srderson Yes, didn't want to simply 'hide' this lint warning...

I like action-able TODOs ;-)

**Comment by srderson** [comment]
LGTM. Thanks!
