### PR TITLE
Issue 1287

### LINKED ISSUE #1287: incorrect header text for license
The recommended license header text is incorrect. Per Mike Dolan, I will be submitting a PR to correct the example. Afterwards, I will create a separate issue and submit PRs to address the broader issue in each file.

### PR DESCRIPTION
**Pull request by christo4ferris**
Fixes #1287 to correct the example license header text

[ci skip]

Signed-off-by: Christopher Ferris chrisfer@us.ibm.com

### CODE REVIEW

**Comment by srderson** [comment]
LGTM. Thanks

File: core/ledger/confighistory/mgr.go [hunk 1]
```diff
@@ -163,7 +169,73 @@ func (r *retriever) CollectionConfigAt(blockNum uint64, chaincodeName string) (*
...
+	if err := nsItr.Error(); err != nil {
+		return nil, errors.Wrap(err, "internal leveldb error while obtaining db iterator")
+
+	}
+	defer nsItr.Release()
+
+	var numCollectionConfigs uint64 = 0
+	for nsItr.Next() {
+		if err := nsItr.Error(); err != nil {
+			return nil, errors.Wrap(err, "internal leveldb error while iterating for txids")
```
Comment (manish-sethi) [inline core/ledger/confighistory/mgr.go]: txids :-)

File: core/ledger/confighistory/mgr.go [hunk 2]
```diff
@@ -163,7 +169,73 @@ func (r *retriever) CollectionConfigAt(blockNum uint64, chaincodeName string) (*
...
+	hasher.Reset()
+	metadataFileWriter, err := snapshot.CreateFile(path.Join(dir, snapshotMetadataFileName), snapshotFileFormat, hasher)
+	if err != nil {
+		return nil, err
+	}
+	defer metadataFileWriter.Close()
+
+	if err = metadataFileWriter.EncodeString(collectionConfigNamespace); err != nil {
+		return nil, err
+	}
```
Comment (manish-sethi) [inline core/ledger/confighistory/mgr.go]: As you are storing the dbkey as is, does this help in any manner?
