### PR TITLE
Fixes #1626. Simplify build behind proxy server

### LINKED ISSUE #1626: Setup devenv on Windows 7 x64 behind proxy server
## Description

I am trying to setup devenv as it is described in [here](https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devenv.md). Everything work as expected except in case when the host I am running vagrant on is behind proxy server. The provisioning process fails with error that Docker can't pull busybox image from remote server.
## Describe How to Reproduce
1. No VMs, everything is clean
2. Configure Windows 7 x64 (env. variables, required software ...) as described on the devenv page.
3. Run `vagrant up` -> Get first error that Docker can't pull busybox image. I believe this is normal, because Docker is being installed during provision step.
4. Run `vagrant provision` -> Get second error that Docker again can't pull busybox image. Before I get this error, I saw that proxy server was configured for Docker. Logs below.

```
D:\go_src\src\github.com\hyperledger\fabric\devenv>vagrant provision
==> default: Configuring proxy for Apt...
==> default: Configuring proxy for Docker...
==> default: Configuring proxy environment variables...
==> default: Configuring proxy for npm...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: ++ export DOCKER_STORAGE_BACKEND=
==> default: ++ DOCKER_STORAGE_BACKEND=
==> default: ++ cd /hyperledger/devenv
==> default: ++ ./setup.sh
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: apt-transport-https is already the newest version.
==> default: ca-certificates is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
==> default: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.3tpe7XUzq7 --no-auto-check-trustdb --trust-mo
del always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E8
9F3A912897C070ADBF76221572C52609D
==> default: gpg:
==> default: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
==> default: gpg:
==> default: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
==> default: gpg:
==> default: Total number processed: 1
==> default: gpg:
==> default:              unchanged: 1
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: apparmor is already the newest version.
==> default: linux-image-extra-3.13.0-85-generic is already the newest version.
==> default: docker-engine is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
==> default: docker stop/waiting
==> default: docker start/running, process 10221
==> default: Unable to find image 'busybox:latest' locally
==> default: Pulling repository docker.io/library/busybox
==> default: docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/busybox/images. You may want to che
ck your internet connection or if you are behind a proxy..
==> default: See 'docker run --help'.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### PR DESCRIPTION
**Pull request by tysonite**
Simplify running devenv on host behind proxy server.
## Description
1. /etc/default/docker file was always overwritten by static content. However, if you try to run vagrant up behind proxy, vagrant will set up env. variables which in turn are placed into /etc/default/docker file and shall be preserved.
2. Pass proxy env. variables into docker build command for the same purpose.
## Motivation and Context

Fixes #1626. Actually, the fix is a partial, as docker being installed on a provision step, vagrant don't set proxy env. variables for it and thus it is required to execute vagrant provision after the first failure on vagrant up step.
## How Has This Been Tested?

Tested vagrant up on host behind proxy and on host directly connected to the Internet.
## Checklist:
- [X] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [X] Either no new documentation is required by this change, OR I added new documentation
- [X] Either no new tests are required by this change, OR I added new tests
- [X] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Mikhail Kulinich tysonite@gmail.com

### CODE REVIEW

File: devenv/setup.sh [hunk 1]
```diff
@@ -70,7 +70,8 @@ esac
 apt-get install -y linux-image-extra-$(uname -r) apparmor docker-engine
 
 # Configure docker
-echo "DOCKER_OPTS=\"-s=${DOCKER_STORAGE_BACKEND_STRING} -r=true --api-cors-header='*' -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock ${DOCKER_OPTS}\"" > /etc/default/docker
+DOCKER_OPTS="-s=${DOCKER_STORAGE_BACKEND_STRING} -r=true --api-cors-header='*' -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock ${DOCKER_OPTS}"
+sed -i.bak '/^DOCKER_OPTS=/{h;s|=.*|=\"'"${DOCKER_OPTS}"'\"|};${x;/^$/{s||DOCKER_OPTS=\"'"${DOCKER_OPTS}"'\"|;H};x}' /etc/default/docker
```
Comment (corecode) [inline devenv/setup.sh:74]: How does this work?  I feel most people will not want to touch this.

Comment (tysonite) [inline devenv/setup.sh:74]: If there is a line "DOCKER_OPTS=" in /etc/default/docker, then replace its value with ${DOCKER_OPTS}. Otherwise, add line DOCKER_OPTS=${DOCKER_OPTS} into /etc/default/docker.

Perhaps, a cleaner way exists to accomplish the same task. My main intention is to easily run vagrant behind proxy. Unfortunately, devenv does not work out of the box if you forced to use proxy.

See [this](http://superuser.com/questions/590630/sed-how-to-replace-line-if-found-or-append-to-end-of-file-if-not-found) answer on SO for more information.

Comment (corecode) [inline devenv/setup.sh:74]: how about just replacing the `>` with `>>`, so that the line is added to the end?  What content do you intend to preserve?

Comment (tysonite) [inline devenv/setup.sh:74]: I need to keep http_proxy, https_proxy, ... which were added by vagrant previously. And, yes, I may change to '>>', I didn't make that because I am not sure how you may use docker's options. But in this case, every time vagrant provision is launched a new line will be appended to /etc/default/docker.

Comment (tysonite) [inline devenv/setup.sh:74]: @corecode Is there any chance that those changes will be merged into mainstream? Let me know, please, if I need to modify something.

Comment (corecode) [inline devenv/setup.sh:74]: I can't merge, sorry.

**Comment by srderson** [comment]
Travis failure is just the consensus 680 test

**Comment by srderson** [comment]
I confirmed that this does not break anything in an env without a proxy. I did not actually test with a proxy, but I'll assume @tysonite's test is valid and if not, others will complain. LGTM

@tysonite could you consider adding documentation at some point with steps for running behind a proxy?

**Comment by tysonite** [comment]
@srderson, thank you.

Should I make an additional PR for [devenv](https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devenv.md) with required steps? Those steps include following:
1) Re-run `vagrant provision' after first failure of 'vagrant up'
2) Setup NO_PROXY env. variable as internally tests depend on IP of peers, which shall be accessed without proxy.
