### PR TITLE
Mutex introduced in Membership Services

### LINKED ISSUE #1800: Missing synchronization around DB operations in Membership Services
## Description

A synchronization mechanism is required for DB operations in order to avoid inconsistencies due to multithreading.
## Describe How to Reproduce

Registering users in parallel using node hlc-tester.js the following error appears in member services
ERROR: 2016/06/07 22:27:53 eca.go:252: database is locked

### PR DESCRIPTION
**Pull request by jeroiraz**
## Description

Provide mutual exclusion in user registration, ecert generation and attributes population.
## Motivation and Context

This change prevents inconsistencies by taking into account multithreading.
Fix  #1800
## How Has This Been Tested?

Unit and behave tests passed
No new test cases have been created as part of this work
## Checklist:
- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff)
- [x] No new documentation is required by this change
- [x] No new tests are required by this change
- [x] I have run [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [go vet](https://golang.org/cmd/vet/), and [golint](https://github.com/golang/lint). I have cleaned up all valid errors and warnings in code I have added or modified. The goal is clean, consistent, and readable code.

Signed-off-by: jeronimo.irazabal jeronimo.irazabal@gmail.com/iraza@ar.ibm.com

### CODE REVIEW

File: membersrvc/ca/ca.go [hunk 1]
```diff
@@ -340,6 +345,9 @@ func (ca *CA) createCertificate(id string, pub interface{}, usage x509.KeyUsage,
 }
 
 func (ca *CA) createCertificateFromSpec(spec *CertificateSpec, timestamp int64, kdfKey []byte) ([]byte, error) {
+	mutex.Lock()
```
Comment (adecaro) [inline membersrvc/ca/ca.go:348]: @jeronimoirazabal Just a clarification, can't we remove this lock by having a db transaction wrapping the sql insert? SQLite3 should support synchronization automatically, no?

Comment (jeroiraz) [inline membersrvc/ca/ca.go:348]: @adecaro Transactions in SQLite3 are serialized but would that ensure concurrent transactions are serialized entirely or could them be interleaved? Would that depend on the underlying database driver? If so I think the advantage of this approach (synchronization handled uniformly in go) would be being independent of how concurrent transactions are handled in the db and being able to have mutex logic at application level instead. Does it make sense?

Comment (adecaro) [inline membersrvc/ca/ca.go:348]: @jeronimoirazabal Yes, it makes sense :) I commented because I'm in general worried about locks. When they are not really needed they just reduce performances.

**Comment by bramwelt** [comment]
reverify jenkins

**Comment by bramwelt** [comment]
reverify jenkins

**Comment by JonathanLevi** [comment]
Yes, aside from the fact that the same locking mechanism is currently in use when requesting TCerts..., I like @jeronimoirazabal 's approach as it also does not introduce any DB/vendor "lock-in". See #718's earlier suggestion to potentially move away from SQLite3?

So, all in all (regardless of Jenkins), this change looks good to me.

**Comment by JonathanLevi** [comment]
@srderson can you please take a quick look at this? The "rather be safe than sorry" approach...

**Comment by srderson** [comment]
LGTM. Thanks for the review @adecaro and thanks for the fix @jeronimoirazabal!
