### PR TITLE
Addressing Issue #2145: Transaction's certificate validation

### LINKED ISSUE #2145: Address certificate verification at the peer level.
## Description

The TODO at line 72 of the file core/crypto/peer_impl.go needs to be addressed. It requests the verification of the transaction certificate.
## Describe How to Reproduce

The peer code does not verify transaction certificate.

### PR DESCRIPTION
**Pull request by adecaro**
## Description

This PR introduces code to ensure that the certificate attached to a transaction is valid meaning that it has been signed by the either the ECA or the TCA.
## Motivation and Context

Fixes #2145 
## How Has This Been Tested?

The tests has been enhanced to verify that a transaction with an invalid certificate fails verification.
## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md#legal-stuff).
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Angelo De Caro adc@zurich.ibm.com

### CODE REVIEW

File: core/crypto/peer_impl.go [hunk 1]
```diff
@@ -69,7 +69,27 @@ func (peer *peerImpl) TransactionPreValidation(tx *obc.Transaction) (*obc.Transa
...
 
-		// TODO: verify cert
+		// Verify transaction certificate against root
+		// DER to x509
+		x509Cert, err := primitives.DERToX509Certificate(tx.Cert)
+		if err != nil {
+			peer.Debugf("Failed parsing certificate [% x]: [%s].", tx.Cert, err)
+
+			return tx, err
+		}
```
Comment (adecaro) [inline core/crypto/peer_impl.go:79]: @JonathanLevi, thanks for comment. Actually, I agree, the function can be converted to a predicate. Let's have this addressed by another issue. Is it okay?

Comment (JonathanLevi) [inline core/crypto/peer_impl.go:79]: @adecaro Just saw your Slack message. Sorry, didn't realize this/my comment was blocking. I was asking/proposing mostly/also out of interest.

Yes, can be done in a separate issue/PR, at some point... sure.

**Comment by srderson** [comment]
LGTM, thanks
